engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: false
ratings:
  paths:
  - "lib/**.js"
exclude_paths:
- bin/**/*
- test/**/*
- doc/**/*
- node_modules/**/*